const FONTE_PADRAO = '600 15px system-ui, sans-serif';
const CONST_TITULO = { LARGURA_MAXIMA: 240, PADDING_HORIZONTAL: 16, PADDING_VERTICAL: 8, ALTURA_MINIMA: 48, ALTURA_LINHA: 22 };
const CONST_ANOTACAO = { PADDING_VERTICAL: 16, PADDING_HORIZONTAL: 20, ALTURA_PAUTA_PADRAO: 26, LARGURA_PADRAO: 420, DENSIDADE_PADRAO: 4.5, MULTIPLICADOR_FOLGA: 1.5, LINHAS_MINIMAS: 3, ALTURA_ILUSTRACAO_PADRAO: 220 };
const CONST_CONECTOR = { LARGURA: 30 };
let _contextoMedicaoCache = null;
function obterContextoMedicao(){if(_contextoMedicaoCache)return _contextoMedicaoCache;const canvas=document.createElement('canvas');const contexto=canvas.getContext('2d');contexto.font=FONTE_PADRAO;_contextoMedicaoCache=contexto;return contexto;}
function quebrarPalavraLonga(palavra,larguraMaxima,contexto){if(contexto.measureText(palavra).width<=larguraMaxima)return[palavra];const partes=[];let atual='';for(const c of palavra){const teste=atual+c;if(contexto.measureText(teste).width<=larguraMaxima||!atual)atual=teste;else{partes.push(atual);atual=c;}}if(atual)partes.push(atual);return partes;}
function quebrarTexto(texto,larguraMaxima,font,contextoExterno){const contexto=contextoExterno||obterContextoMedicao();const anterior=contexto.font;contexto.font=font||FONTE_PADRAO;const palavras=String(texto||'').trim().split(/\s+/).filter(Boolean),linhas=[];let atual='';palavras.forEach(palavra=>{if(contexto.measureText(palavra).width>larguraMaxima){if(atual){linhas.push(atual);atual='';}const partes=quebrarPalavraLonga(palavra,larguraMaxima,contexto);partes.slice(0,-1).forEach(parte=>linhas.push(parte));atual=partes[partes.length-1]||'';return;}const teste=atual?`${atual} ${palavra}`:palavra;if(!atual||contexto.measureText(teste).width<=larguraMaxima)atual=teste;else{linhas.push(atual);atual=palavra;}});if(atual)linhas.push(atual);contexto.font=anterior;return linhas.length?linhas:[''];}
function calcularDimensaoTitulo(titulo){const linhas=quebrarTexto(titulo,CONST_TITULO.LARGURA_MAXIMA-CONST_TITULO.PADDING_HORIZONTAL*2,FONTE_PADRAO);return{largura:CONST_TITULO.LARGURA_MAXIMA,altura:Math.max(CONST_TITULO.ALTURA_MINIMA,CONST_TITULO.PADDING_VERTICAL*2+linhas.length*CONST_TITULO.ALTURA_LINHA),linhasQuebradas:linhas.length,linhasTexto:linhas};}
function calcularLinhasFinaisAnotacao(anotacao){if(anotacao.linhasManuais)return Math.max(CONST_ANOTACAO.LINHAS_MINIMAS,anotacao.linhasManuais);const base=Math.ceil(anotacao.palavrasEstimadas/CONST_ANOTACAO.DENSIDADE_PADRAO);return Math.max(CONST_ANOTACAO.LINHAS_MINIMAS,Math.ceil(base*CONST_ANOTACAO.MULTIPLICADOR_FOLGA));}
function calcularDimensaoAnexo(anexo){if(!anexo)return null;return{largura:CONST_ANOTACAO.LARGURA_PADRAO,altura:typeof anexo.altura==='number'&&anexo.altura>0?anexo.altura:220,tipo:'ilustracao'};}
function calcularDimensaoAnotacao(anotacao,escalaEntrelinha){if(!anotacao)return null;const largura=CONST_ANOTACAO.LARGURA_PADRAO;let resultado;if(anotacao.tipo==='ilustracao')resultado={largura,altura:anotacao.alturaCustomizada||220,linhasFinais:null,tipo:'ilustracao',entrelinha:null};else{const entrelinha=typeof escalaEntrelinha==='number'&&escalaEntrelinha>0?escalaEntrelinha:26,linhasFinais=calcularLinhasFinaisAnotacao(anotacao);resultado={largura,altura:CONST_ANOTACAO.PADDING_VERTICAL*2+linhasFinais*entrelinha,linhasFinais,tipo:'pauta',entrelinha,paddingVertical:16,paddingHorizontal:20};}resultado.anexo=calcularDimensaoAnexo(anotacao.anexo);return resultado;}
function enriquecerArvoreComDimensoes(no,escala){const titulo=calcularDimensaoTitulo(no.titulo),anotacao=calcularDimensaoAnotacao(no.anotacao,escala);let larguraTotal=titulo.largura,alturaTotal=titulo.altura;if(anotacao){larguraTotal+=30+anotacao.largura;alturaTotal=Math.max(alturaTotal,anotacao.altura);if(anotacao.anexo){larguraTotal+=30+anotacao.anexo.largura;alturaTotal=Math.max(alturaTotal,anotacao.anexo.altura);}}no.dimensoes={titulo,anotacao,unidadeComposta:{larguraTotal,alturaTotal}};no.filhos.forEach(f=>enriquecerArvoreComDimensoes(f,escala));return no;}
